import axios from 'axios'

export const getaccount = (search) => () => axios.get(`/api/admin/account?s_id=${search.s_id}&s_name=${search.s_name}`).then((res) => res.data)
export const getsearchcategory = (search) => () => axios.get(`/api/category?s_id=${search.s_id}&s_name=${search.s_name}`).then((res) => res.data)
export const addbrand = async (brand) => axios.post('/api/manager/addbrand', { brand: brand, isupdated: false })
export const gersearchrole = (search) => () => axios.get(`/api/admin/role?s_name=${search.s_name}&s_permission=${search.s_permission}`).then((res) => res.data)
export const addcate = async (category) => await axios.post('/api/manager/addcategory', { category: category, isupdated: false })
export const addrole = async (role) => await axios.post('/api/admin/addrole', { role: role, isupdated: false })
export const updaterole = async (role) => await axios.post('/api/admin/addrole', { role: role, isupdated: true })
export const updatecate = async (category) => await axios.post('/api/manager/addcategory', { category: category, isupdated: true })
export const updateidcate = async (category, oldid) => await axios.post('/api/manager/addcategory', { category: category, isupdated: true, isupdatedid: true, oldid: oldid })
export const getsearchproduct = (search) => () => axios.get(`/api/product`, { params: search }).then((res) => res.data)
export const getcategory = () => axios.get(`/api/category`).then((res) => res.data)
export const getbrand = () => axios.get(`/api/brand`).then((res) => res.data)
export const getcart = () => axios.get(`/api/user/cart`).then((res) => res.data)
export const getrole = () => axios.get(`/api/admin/role`).then((res) => res.data)
export const gettinhthanh = () =>  axios.get(`https://raw.githubusercontent.com/kenzouno1/DiaGioiHanhChinhVN/master/data.json`).then((res) => res.data)
export const getbrandbyid = (id) => () => axios.get(`/api/brand?id=${id}`).then((res) => res.data)
export const updatebrand = async (brand) => await axios.post('/api/manager/addbrand', { brand: brand, isupdated: true })
export const updatebrandwithid = async (brand, id) => axios.post('/api/manager/addbrand', { brand: brand, isupdated: true, isupdatedid: true, oldid: id })
export const addproduct = async (productform) => await axios.post('/api/manager/addproduct', productform, { headers: { 'Content-Type': 'multipart/form-data' } })
export const updateproduct = async (productform) => await axios.post('/api/manager/addproduct', productform, { headers: { 'Content-Type': 'multipart/form-data' } })
export const getdatainvoice = (month)=>() => axios.get(`/api/manager/datainvoice?month=${month}`).then((res) => res.data)
export const searchbrand = (search)=>() => axios.get(`/api/brand?s_id=${search.s_id}&s_name=${search.s_name}`).then((res) => res.data)
export const deletebrand = async (brand) => await axios.post('/api/manager/deletebrand', { id: brand.id })
export const deletecate = async (category) => await axios.post('/api/manager/deletecate', { id: category.id })
export const deleteinvoice = async (invoice) => await axios.post('/api/manager/deleteinvoice', { id: invoice.id })
export const deletepro = async (product) => await axios.post('/api/manager/deletepro', { id: product.id })
export const deletecart = async (proid,cartid) => await axios.post('/api/user/deletecart', { proid: proid, cartid: cartid })
export const deleterole = async (id) => await axios.post('/api/admin/deleterole', { id:id})
export const register = async (form) => await axios.post('/api/register', { form: form })
export const changepass = async (form) => await axios.post('/api/user/changepass', { form: form })
export const gettotalinvoice =  () =>  axios.get('/api/manager/totalinvoice').then((res) => res.data)

export const getbestsaler = () => axios.get(`/api/manager/bestsaler`).then((res) => res.data)
export const getdatainvoicebymonth = () => axios.get(`/api/manager/datainvoicebymonth`).then((res) => res.data)
export const updatecart = async(proid,cartid,quantity)=> await axios.post('/api/user/updatecart', { proid: proid, cartid: cartid,quantity:quantity })
export const getproductbycate = () => axios.get(`/api/productbycate`).then((res) => res.data)
export const getcartdetail = (params)=> () => axios.get(`/api/user/cartdetail`, { params: { id: params.id } }).then((res) => res.data)
export const gethistory = () => axios.get(`/api/user/history`).then((res) => res.data)
export const getproductdetail = (id)=> () => axios.get(`/api/productdetail?id=${id}`).then((res) => res.data)
export const gettotaluser = () => axios.get(`/api/manager/totaluser`).then((res) => res.data)
